### ISSUE TITLE
How to specify the readingtime for galery and article posts?

### ISSUE THREAD

**Issue by Djas2017** [Lednerb/bilberry-hugo-theme#121] opened 2018-09-18 10:09 UTC
Hi,

The parameter `showReadingTime = true` is set in the config.toml file.
But I didn't find in the documentation how to specify the amount of time (ex: 5 minutes)

What are the supported units (Minutes, seconds, ...??)

**Comment by Lednerb** [comment] 2018-09-18 18:18
It's the Hugo built in feature that estimates the reading time in minutes based on the words of your article / post.

If enabled it should update automatically and be displayed in the post's meta area like the categories, author and so on.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 18. Sep. 2018, 13:09, Djas2017 schrieb:

**Comment by Djas2017** [comment] 2018-09-18 18:54
Ah, ok! I didn't know that hugo estimates the reading time automatically.

In my use case, I have some articles which will only contain a summary and a link to the original article. And ideally, I want the Reading time to be the time required (estimate) to read the original (external) article. Hugo automatically returns the reading time of the summary text only. An estimate which not includes the reading time of the original article. 

I do not if this makes sense for others too and is something that can be done?
_____________________________________________________________________
Ex: This is my artcile summary: 
This is a premium theme for HUGO, inspired by the Lingonberry WordPress theme from Anders Norén.
Bilberry is an adaption that comes with different optimizations and little features as listed below.
Click here for a DEMO / PREVIEW. If you like this theme and/or use it for commercial purposes, please support me!

To read more visit: https://github.com/Lednerb/bilberry-hugo-theme 
_____________________________________________________________________

I found some resources for reference:
- https://discourse.gohugo.io/t/readingtime-define/13036/5
- https://kodify.net/hugo/strings/reading-time-text/  (How to calculate the reading time of a Hugo string in minutes and seconds?)

Thanks

**Comment by Lednerb** [comment] 2018-09-18 20:29
At the moment this can't be displayed as you would need it, but I think there are two approaches we can go with:

1. Add an option to overwrite the automatically estimated reading time
2. Add an option for a custom meta fields, that can be defined in the site's config file and a users could add to their archetype to add this to their content.

Both would be nice features someone maybe has a use case for.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 18. Sep. 2018, 21:55, Djas2017 schrieb:

**Comment by Djas2017** [comment] 2018-09-19 15:19
Great!
You mean adding an option in the content index.md files where the user can specify something like:
`reading time: 6 minutes`
in addition to the author, categories, etc.

Just to get an idea, and based on your priorities and availability, when could you get this added?

**Comment by Lednerb** [comment] 2018-09-19 16:12
Until mid of next week I'm in the Ukrain to celebrate with my wife our wedding that was earlier this year.

So I think this can be added maybe in the first week of October, maybe end of September.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 19. Sep. 2018, 18:20, Djas2017 schrieb:

**Comment by Djas2017** [comment] 2018-09-19 18:03
Congrats and enjoy these great times.

**Comment by Lednerb** [comment] 2018-09-20 08:41
Thanks! Closing here because the issue is split into  #126  and #124.

**Closed by Lednerb** 2018-09-20 08:41 UTC
Labels: documentation

**Comment by Lednerb** [comment] 2020-07-28 09:43
Hello @Djas2017 

after a long time the requested feature is now available in the latest version in the `master` branch.

Further information in the `README.md` and in #124

**Comment by Djas2017** [comment] 2020-07-28 19:59
Good. Thank you.
Hope it will be useful to others too.
